name: B2M MLOps Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v3

    - name: Installation de Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Installation des dépendances
      run: |
        python -m pip install --upgrade pip
        pip install pandas xgboost scikit-learn joblib fastapi uvicorn pytest httpx

    - name: Vérification de la structure
      run: |
        ls -R
        
    - name: Test d'entraînement (Dry Run)
      run: |
        export PYTHONPATH=.
        python3 -m src.train
        
    - name: Lancement des tests unitaires
      run: |
        export PYTHONPATH=.
        # On lancera pytest ici quand on aura créé le dossier tests
        echo "Tests validés"
