name: B2M MLOps Pipeline CI

on:
  push:
    # On ajoute 'developpement' car c'est là que tu travailles actuellement
    branches: [ main, master, developpement ]
  pull_request:
    branches: [ main, master, developpement ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4 # Version plus récente

    - name: Installation de Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' # Synchronisé avec ton Docker

    - name: Installation des dépendances
      run: |
        python -m pip install --upgrade pip
        # On installe tout d'un coup via ton fichier officiel
        pip install -r requirements.txt
        pip install pytest httpx 

    - name: 📂 Vérification de la structure (Debug)
      run: ls -R
        
    - name: 🧪 Test du Data Manager (Dry Run)
      run: |
        # On définit le PYTHONPATH pour que les imports src.xxx fonctionnent
        export PYTHONPATH=$PYTHONPATH:.
        # On lance le manager pour voir s'il génère bien les artefacts
        python3 PROJET_MLOPS_B2M/src/data_manager.py
        
    - name: ⚙️ Lancement des tests unitaires
      run: |
        export PYTHONPATH=$PYTHONPATH:.
        # Pytest va chercher tous les fichiers test_*.py dans ton projet
        pytest