name: CI/CD Pipeline

on:
  push:
    branches: [ developpement, main ] # Se déclenche quand tu push sur l'une de ces branches

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # On pousse la branche locale actuelle vers la branche main de Hugging Face
          # La syntaxe 'HEAD:main' est magique : elle prend ta branche actuelle (peu importe son nom)
          git push --force https://baibrahima:$HF_TOKEN@huggingface.co/spaces/baibrahima/PROJET_MLOPS_B2M HEAD:main